@startuml
Title Carport
|Customer|
start
:Goes to website;
|#AntiqueWhite|Website|

:Got a user?;

fork

    :Yes;
fork again

    :No;
    :Insert user data;
    |Database|
    :Save user data;
    |Website|
    end fork

:login;
|Database|
:Get user information;
|Website|
:Select carport values;

|Customer|
:Accept and ask for an offer;
|Website|
:Give Ordernumber;

|Database|
:Save all date;

|Shop|
:Getting request;
:Set the requested data into another program;

|Website|
:Generate item list;
:Generate SVG;

|Database|
:Save BoM data;

|Shop|
:Call customer;
:Give an offer;

|Database|
:Save offer data;


|Customer|
:Go to website;
:See offer;
:Accept offer;

|Website|


fork
    |Website|
    :Open up for SVG and BoM data;

    |Customer|
    :request BoM and SVG data;
    |Database|
    :Get BoM and SVG;
    |Website|
    :Show BoM and SVG;
    |Customer|
    :Print Userguide, BoM and SVG;

fork again
    |Shop|
    :Get order;
    :Find all components on BoM;
    :Package and deliver it to the customer;
end fork
|Customer|
:Get the delivery;
:Check the deliver is in check;
:Start building the Carport;
stop
@enduml